# Classification with stumbleupon data

Project 4 has been changed since scraping was untenable. The project now focuses on the stumbleupon kaggle dataset. For more information on this dataset, [check out the website here](https://www.kaggle.com/c/stumbleupon).

---

## 1. Load in the dataset

This is the only part completed for you.

---

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('white')

%matplotlib inline

In [2]:
# The delimiter removes the tabs
su = pd.read_csv('../dataset/evergreen.tsv', delimiter='\t')
su.head()

url  urlid  \
0  http://www.bloomberg.com/news/2010-12-23/ibm-p...   4042   
1  http://www.popsci.com/technology/article/2012-...   8471   
2  http://www.menshealth.com/health/flu-fighting-...   1164   
3  http://www.dumblittleman.com/2007/12/10-foolpr...   6684   
4  http://bleacherreport.com/articles/1205138-the...   9006   

                                         boilerplate alchemy_category  \
0  {"title":"IBM Sees Holographic Calls Air Breat...         business   
1  {"title":"The Fully Electronic Futuristic Star...       recreation   
2  {"title":"Fruits that Fight the Flu fruits tha...           health   
3  {"title":"10 Foolproof Tips for Better Sleep "...           health   
4  {"title":"The 50 Coolest Jerseys You Didn t Kn...           sports   

  alchemy_category_score  avglinksize  commonlinkratio_1  commonlinkratio_2  \
0               0.789131     2.055556           0.676471           0.205882   
1               0.574147     3.677966           0.508021           0.288770   
2               0.996526     2.382883           0.562016           0.321705   
3               0.801248     1.543103           0.400000           0.100000   
4               0.719157     2.676471           0.500000           0.222222   

   commonlinkratio_3  commonlinkratio_4  ...    is_news  lengthyLinkDomain  \
0           0.047059           0.023529  ...          1                  1   
1           0.213904           0.144385  ...          1                  1   
2           0.120155           0.042636  ...          1                  1   
3           0.016667           0.000000  ...          1                  0   
4           0.123457           0.043210  ...          1                  1   

   linkwordscore  news_front_page  non_markup_alphanum_characters  \
0             24                0                            5424   
1             40                0                            4973   
2             55                0                            2240   
3             24                0                            2737   
4             14                0                           12032   

   numberOfLinks  numwords_in_url parametrizedLinkRatio  \
0            170                8              0.152941   
1            187                9              0.181818   
2            258               11              0.166667   
3            120                5              0.041667   
4            162               10              0.098765   

   spelling_errors_ratio  label  
0               0.079130      0  
1               0.125448      1  
2               0.057613      1  
3               0.100858      1  
4               0.082569      0  

[5 rows x 27 columns]

## 2. Clean up/examine your data

Some of the columns may have values that need changing or that are of the wrong type. There could also be columns that aren't very useful.

---

In [3]:
#Doing some examination of the data
su.describe()

urlid  avglinksize  commonlinkratio_1  commonlinkratio_2  \
count   7395.000000  7395.000000        7395.000000        7395.000000   
mean    5305.704665     2.761823           0.468230           0.214080   
std     3048.384114     8.619793           0.203133           0.146743   
min        1.000000     0.000000           0.000000           0.000000   
25%     2688.500000     1.602062           0.340370           0.105263   
50%     5304.000000     2.088235           0.481481           0.202454   
75%     7946.500000     2.627451           0.616604           0.300000   
max    10566.000000   363.000000           1.000000           1.000000   

       commonlinkratio_3  commonlinkratio_4  compression_ratio  embed_ratio  \
count        7395.000000        7395.000000        7395.000000  7395.000000   
mean            0.092062           0.049262           2.255103    -0.103750   
std             0.095978           0.072629           5.704313     0.306545   
min             0.000000           0.000000           0.000000    -1.000000   
25%             0.022222           0.000000           0.442616     0.000000   
50%             0.068627           0.022222           0.483680     0.000000   
75%             0.133333           0.065065           0.578227     0.000000   
max             0.980392           0.980392          21.000000     0.250000   

       framebased  frameTagRatio     ...        html_ratio  image_ratio  \
count      7395.0    7395.000000     ...       7395.000000  7395.000000   
mean          0.0       0.056423     ...          0.233778     0.275709   
std           0.0       0.041446     ...          0.052487     1.919320   
min           0.0       0.000000     ...          0.045564    -1.000000   
25%           0.0       0.028502     ...          0.201061     0.025900   
50%           0.0       0.045775     ...          0.230564     0.083051   
75%           0.0       0.073459     ...          0.260770     0.236700   
max           0.0       0.444444     ...          0.716883   113.333333   

       lengthyLinkDomain  linkwordscore  non_markup_alphanum_characters  \
count        7395.000000    7395.000000                     7395.000000   
mean            0.660311      30.077079                     5716.598242   
std             0.473636      20.393101                     8875.432430   
min             0.000000       0.000000                        0.000000   
25%             0.000000      14.000000                     1579.000000   
50%             1.000000      25.000000                     3500.000000   
75%             1.000000      43.000000                     6377.000000   
max             1.000000     100.000000                   207952.000000   

       numberOfLinks  numwords_in_url  parametrizedLinkRatio  \
count    7395.000000      7395.000000            7395.000000   
mean      178.754564         4.960649               0.172864   
std       179.466198         3.233111               0.183286   
min         1.000000         0.000000               0.000000   
25%        82.000000         3.000000               0.040984   
50%       139.000000         5.000000               0.113402   
75%       222.000000         7.000000               0.241299   
max      4997.000000        22.000000               1.000000   

       spelling_errors_ratio        label  
count            7395.000000  7395.000000  
mean                0.101221     0.513320  
std                 0.079231     0.499856  
min                 0.000000     0.000000  
25%                 0.068739     0.000000  
50%                 0.089312     1.000000  
75%                 0.112376     1.000000  
max                 1.000000     1.000000  

[8 rows x 21 columns]

In [4]:
su.dtypes

url                                object
urlid                               int64
boilerplate                        object
alchemy_category                   object
alchemy_category_score             object
avglinksize                       float64
commonlinkratio_1                 float64
commonlinkratio_2                 float64
commonlinkratio_3                 float64
commonlinkratio_4                 float64
compression_ratio                 float64
embed_ratio                       float64
framebased                          int64
frameTagRatio                     float64
hasDomainLink                       int64
html_ratio                        float64
image_ratio                       float64
is_news                            object
lengthyLinkDomain                   int64
linkwordscore                       int64
news_front_page                    object
non_markup_alphanum_characters      int64
numberOfLinks                       int64
numwords_in_url                   

In [5]:
# Creating value counts function
def count(x):
    counts = su[x].value_counts()
    return counts
    
print count('hasDomainLink')

0    7238
1     157
Name: hasDomainLink, dtype: int64


In [6]:
# Deleting the framebased column because all the values are 0
del su['framebased']

## 3. Use statsmodels' logistic regression function to look at variable significance

The **`import statsmodels.formula.api as smf`** code below gives us access to a statsmodels api that can run logistic regressions using patsy-style formulas.

Ex:

```python
formula = 'target ~ var1 + var2 + C(var3) -1'
logreg = smf.logit(formula, data=data)
logreg_results = logreg.fit()
print logreg_results.summary()
```

---

In [7]:
# Creating a couple of masks. The non_numeri_col is the columns that are not floats or integers
# The numeri_col is the ones that are floats and integers
non_numeri_col = ['label', 'url', 'boilerplate', 'alchemy_category', 'alchemy_category_score', 'is_news', 'news_front_page']
numeri_col = [x for x in su.columns if not x in non_numeri_col]
target = 'label'

In [8]:
# Normalizing the numeric columns
su[numeri_col] = (su[numeri_col] - np.mean(su[numeri_col]))/np.std(su[numeri_col])

In [9]:
# Finding the index of the numeric columns and then replacing them with the normalizes values
su.ix[:, numeri_col] = su[numeri_col]

In [10]:
import statsmodels.formula.api as smf

### 3.1 Run a logistic regression predicting evergreen from the numeric columns

And print out the results as shown in the example above.

---

In [11]:
# The negative 1 removes the intercept as other Scikit learn functions will add in an intercept and it will duplicate the
# the intercept
formula1 = 'label ~ avglinksize + spelling_errors_ratio + news_front_page + numwords_in_url + is_news -1'
logreg1 = smf.logit(formula1, data=su)
logreg_result1 = logreg1.fit()
print logreg_result1.summary()
# Remember that the P>|z| score essentially an indicater of how random the predicter is. A score of 0 mean that it is a non-random
# prediction. For example: THe spelling_errors_ratio is a strong predictor as the score of 0 means that increases in spelling errors
# have a highly predictable negative effect on the label binary.

Optimization terminated successfully.
         Current function value: 0.690069
         Iterations 4
                           Logit Regression Results                           
Dep. Variable:                  label   No. Observations:                 7395
Model:                          Logit   Df Residuals:                     7388
Method:                           MLE   Df Model:                            6
Date:                Mon, 16 May 2016   Pseudo R-squ.:                0.003930
Time:                        12:55:09   Log-Likelihood:                -5103.1
converged:                       True   LL-Null:                       -5123.2
                                        LLR p-value:                 4.027e-07
                            coef    std err          z      P>|z|      [95.0% Conf. Int.]
-----------------------------------------------------------------------------------------
news_front_page[0]        0.0883      0.031      2.857      0.004         0.028     0.

### 3.2 Run a logistic regression predicting evergreen from the numeric columns and a categorical variable of alchemy_category

And print out the results as shown in the example.

---

In [12]:
formula2 = 'label ~ avglinksize + spelling_errors_ratio + news_front_page + numwords_in_url + is_news + alchemy_category -1'
logreg2 = smf.logit(formula2, data=su)
logreg_result2 = logreg2.fit()
print logreg_result2.summary()

         Current function value: 0.647053
         Iterations: 35
                           Logit Regression Results                           
Dep. Variable:                  label   No. Observations:                 7395
Model:                          Logit   Df Residuals:                     7375
Method:                           MLE   Df Model:                           19
Date:                Mon, 16 May 2016   Pseudo R-squ.:                 0.06602
Time:                        12:55:09   Log-Likelihood:                -4785.0
converged:                      False   LL-Null:                       -5123.2
                                        LLR p-value:                3.439e-131
                                             coef    std err          z      P>|z|      [95.0% Conf. Int.]
----------------------------------------------------------------------------------------------------------
news_front_page[0]                         0.0901      0.055      1.639      0.101      

/Users/mikesanders/anaconda/lib/python2.7/site-packages/statsmodels/base/model.py:466: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)


## 4. Use sklearn to cross-validate the accuracy of the model above

Normalize the numeric and categorical columns of the predictor matrix.

---

In [13]:
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [14]:
x = su[numeri_col]
y = su[target]

In [15]:
X_train, x_test, Y_train, y_test = train_test_split(x,y, test_size=.3 )

logreg.fit(X_train, Y_train)
logreg.predict(x_test)
print logreg.score(x_test,y_test)

logreg.fit(x,y)
logreg.predict(x)
print logreg.score(x,y)

0.621451104101
0.629479377958


In [16]:
logreg_scores = cross_val_score(logreg,x,y,cv=5)
print logreg_scores
print np.mean(logreg_scores)

[ 0.62297297  0.62880325  0.61663286  0.61392833  0.64276049]
0.625019579109


## 5. Gridsearch regularization parameters for logistic regression

Find the best regularization type (Ridge, Lasso) across a set of regularization strengths.

[NOTE: C is the inverse of the regularization strength. Lower C values are stronger regularization. Having a C higher than 1 will significantly slow down the search. I'm not particularly interested in values over 1, since this is the default regularization strength in LogisticRegression.]

**After you find the best set of parameters, build a Logistic Regression with those parameters and crossvalidate the score.**

[NOTE 2: to run Lasso regularization the solver should be `'liblinear'`]

---

In [17]:
from sklearn.grid_search import GridSearchCV

In [18]:
#Attempting a Lasso
from sklearn.linear_model import LassoCV
lasso = LassoCV()
print lasso.fit(x, y)
print lasso.predict(x)
print "alpha:", lasso.alpha_
print lasso.score(x, y)

LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
    max_iter=1000, n_alphas=100, n_jobs=1, normalize=False, positive=False,
    precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
    verbose=False)
[ 0.49447681  0.43169012  0.39515143 ...,  0.3280733   0.3182466
  0.33096543]
alpha: 0.00307309299289
0.074652799703


In [43]:
lr = LogisticRegression()
scores = cross_val_score(lr, x, y, cv=5)
print scores
print np.mean(scores)

[ 0.62297297  0.62880325  0.61663286  0.61392833  0.64276049]
0.625019579109


In [41]:
np.mean(y)

0.5133198106828939

In [19]:
lasso_scores = cross_val_score(lasso,x,y,cv=5)
print lasso_scores
print np.mean(lasso_scores)

[ 0.06764131  0.0749736   0.05270019  0.0586671   0.08675489]
0.0681474172988


In [20]:
# Running a gridseach for my ridge CV
from sklearn.linear_model import RidgeCV
ridge = RidgeCV()
print ridge.fit(x, y)
print ridge.predict(x)
print "alpha:", ridge.alpha_
print ridge.score(x, y)

RidgeCV(alphas=(0.1, 1.0, 10.0), cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)
[ 0.48918181  0.42408696  0.38711455 ...,  0.30802959  0.31010472
  0.31228117]
alpha: 10.0
0.0762871103676


In [21]:
ridge_scores = cross_val_score(ridge,x,y,cv=5)
print ridge_scores
print np.mean(ridge_scores)

[ 0.06702269  0.07597336  0.04912193  0.05508989  0.09451051]
0.0683436775244


In [47]:

from sklearn.grid_search import GridSearchCV

logreg = LogisticRegression()
Cs = 1.0/np.logspace(-1,4,20)

search_parameters_log = {
    'penalty': ['l1','l2'],
    'C': Cs,
    'class_weight': [None, 'balanced'],
    'solver': ['liblinear'],
    'n_jobs': [4],
    }
logreg_est = GridSearchCV(logreg, search_parameters_log, cv=10)

In [23]:
logreg_est.get_params().keys()

['n_jobs',
 'verbose',
 'estimator__penalty',
 'param_grid',
 'cv',
 'scoring',
 'estimator__verbose',
 'pre_dispatch',
 'estimator__intercept_scaling',
 'fit_params',
 'estimator__max_iter',
 'estimator__warm_start',
 'estimator__solver',
 'refit',
 'iid',
 'estimator__dual',
 'estimator__fit_intercept',
 'estimator__n_jobs',
 'estimator__class_weight',
 'estimator__C',
 'estimator__random_state',
 'estimator',
 'error_score',
 'estimator__multi_class',
 'estimator__tol']

In [48]:
logreg_grid = logreg_est.fit(X_train,Y_train)
# grid.grid_scores_

# for params, mean_acc, std in grid.grid_scores_:
#     print 'C:', params['C']
#     print 'penalty:', params['penalty']
#     print 'class_weight:', params['class_weight']
#     print 'mean accuracy' , mean_acc
#     print '-------------------------------------\n'

In [49]:
print "Best C / Regularization Param:", logreg_grid.best_estimator_.C # This estimator.best_estimator_ object has many great reporting metrics
print "Best Params:", logreg_grid.best_params_
print "Best Score:", logreg_grid.best_score_

Best C / Regularization Param: 0.483293023857
Best Params: {'penalty': 'l1', 'C': 0.48329302385717543, 'n_jobs': 4, 'solver': 'liblinear', 'class_weight': 'balanced'}
Best Score: 0.619204018547


## 6. Gridsearch neighbors for kNN

Find the best number of neighbors with your predictors to predict the `label` target variable.

Start by bulding a kNN model with a set number of neighbors, then use gridsearch to run through a series of neighbors.

---

In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [69]:
# print knn.fit(x,y)
print knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')


In [28]:
print knn.predict(x)[0:5]
print knn.predict(x_test)[0:5]

[1 0 1 0 0]
[1 1 0 1 0]


In [29]:
print knn.predict_proba(x)[0:5]
print knn.predict_proba(x_test)[0:5]

[[ 0.4  0.6]
 [ 0.8  0.2]
 [ 0.2  0.8]
 [ 0.6  0.4]
 [ 0.6  0.4]]
[[ 0.2  0.8]
 [ 0.   1. ]
 [ 0.6  0.4]
 [ 0.4  0.6]
 [ 0.6  0.4]]


In [70]:
print knn.score(X_train, Y_train)

0.754443585781


In [ ]:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [90]:
search_parameters_knn = {
    
    'weights': ['uniform'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size': [30],
    'n_neighbors': [5],
    'n_jobs': [1],
    'p': [2],
    'metric': ['minkowski']
    }

knn_est = GridSearchCV(KNeighborsClassifier(), search_parameters_knn)

In [78]:
# knn_est.get_params().keys()

In [88]:
len(knn_grid.grid_scores_)

40

In [91]:
knn_grid = knn_est.fit(X_train,Y_train)

In [92]:
print "Best Params:", knn_grid.best_params_
print "Best Score:", knn_grid.best_score_

Best Params: {'n_neighbors': 5, 'n_jobs': 1, 'algorithm': 'auto', 'metric': 'minkowski', 'p': 2, 'weights': 'uniform', 'leaf_size': 30}
Best Score: 0.61727202473


## 7. Choose a new target from alchemy_category to predict with logistic regression

**Ideally your category choice will have a small fraction of the total rows, but not TOO small!**

---

### 7.1 Chose your target category, create the Y vector, and check the fraction of instances

---

In [35]:
su['alchemy_category'].value_counts()

?                     2342
recreation            1229
arts_entertainment     941
business               880
health                 506
sports                 380
culture_politics       343
computer_internet      296
science_technology     289
gaming                  76
religion                72
law_crime               31
unknown                  6
weather                  4
Name: alchemy_category, dtype: int64

In [60]:
su['ane_binary'] = su['alchemy_category'].map(lambda x: 1 if x=='arts_entertainment' else 0)
su.tail()

url     urlid  \
7390  http://techcrunch.com/2010/09/08/kno-raises-46...  1.198190   
7391  http://www.uncoached.com/category/why-i-miss-c...  1.177522   
7392  http://eatthis.menshealth.com/slide/sweet-pota... -1.349890   
7393                          http://naturallyella.com/  0.100485   
7394  http://sportsillustrated.cnn.com/2011_swimsuit... -1.711089   

                                            boilerplate    alchemy_category  \
7390  {"title":"Kno Raises 46 Million More To Build ...   computer_internet   
7391  {"title":"Why I Miss College ","body":"Mar 30 ...    culture_politics   
7392  {"title":"Sweet Potatoes Eat This Not That  i'...          recreation   
7393  {"title":"Naturally Ella ","body":" ","url":"n...  arts_entertainment   
7394  {"title":"Esti Ginzburg Swimsuit by Letarte by...                   ?   

     alchemy_category_score  avglinksize  commonlinkratio_1  \
7390               0.651067     0.028855           0.032085   
7391                0.14192    -0.064248           0.074355   
7392               0.196273    -0.088387          -0.750499   
7393               0.617876    -0.201353          -1.268731   
7394                      ?    -0.186051           0.185539   

      commonlinkratio_2  commonlinkratio_3  commonlinkratio_4    ...      \
7390           0.055491           1.040482           1.964328    ...       
7391           0.222082          -0.577208          -0.311131    ...       
7392          -0.293236           0.137549           0.046395    ...       
7393          -1.100288          -0.959265          -0.678320    ...       
7394           1.464663          -0.712645          -0.678320    ...       

      lengthyLinkDomain  linkwordscore  news_front_page  \
7390           0.717243       0.388536                0   
7391           0.717243       0.192378                0   
7392           0.717243       0.633734                0   
7393          -1.394227       0.339497                1   
7394          -1.394227       2.350116                ?   

      non_markup_alphanum_characters  numberOfLinks  numwords_in_url  \
7390                       -0.394103      -0.444429         1.868095   
7391                       -0.005025       0.675635        -0.297148   
7392                       -0.548585      -0.572595         0.012172   
7393                       -0.600642      -0.784349        -1.534430   
7394                       -0.586107       0.887388        -0.297148   

     parametrizedLinkRatio  spelling_errors_ratio  label ane_binary  
7390             -0.722746              -0.376043      0          0  
7391             -0.834077               0.103905      0          0  
7392              1.425993               0.207336      1          0  
7393             -0.799616               2.929770      1          1  
7394             -0.910918               0.415593      0          0  

[5 rows x 27 columns]

### 7.2 Use patsy to create an X matrix of the numeric predictors and all two-way interactions between them

Ex:

```python
import patsy

formula_interactions = '~ (var1 + var2 + var3)**2 -1'
X_interactions = patsy.dmatrix(formula_interactions, data=data
```

Get the column names from the `design_info` property of the patsy X matrix.

---

In [67]:
import patsy
target = 'ane_binary'
Y = su[target]

In [63]:
formula_interactions = '~(avglinksize + spelling_errors_ratio + news_front_page + numwords_in_url + is_news -1)**2 -1'
X_interactions = patsy.dmatrix(formula_interactions, data = su)

In [64]:
X_interactions

DesignMatrix with shape (7395, 21)
  Columns:
    ['news_front_page[0]',
     'news_front_page[1]',
     'news_front_page[?]',
     'is_news[T.?]',
     'news_front_page[T.1]:is_news[T.?]',
     'news_front_page[T.?]:is_news[T.?]',
     'avglinksize',
     'avglinksize:news_front_page[T.1]',
     'avglinksize:news_front_page[T.?]',
     'avglinksize:is_news[T.?]',
     'spelling_errors_ratio',
     'spelling_errors_ratio:news_front_page[T.1]',
     'spelling_errors_ratio:news_front_page[T.?]',
     'spelling_errors_ratio:is_news[T.?]',
     'numwords_in_url',
     'news_front_page[T.1]:numwords_in_url',
     'news_front_page[T.?]:numwords_in_url',
     'numwords_in_url:is_news[T.?]',
     'avglinksize:spelling_errors_ratio',
     'avglinksize:numwords_in_url',
     'spelling_errors_ratio:numwords_in_url']
  Terms:
    'news_front_page' (columns 0:3)
    'is_news' (column 3)
    'news_front_page:is_news' (columns 4:6)
    'avglinksize' (column 6)
    'avglinksize:news_front_page' (colum

In [65]:
X_interactions.design_info

DesignInfo(['news_front_page[0]',
            'news_front_page[1]',
            'news_front_page[?]',
            'is_news[T.?]',
            'news_front_page[T.1]:is_news[T.?]',
            'news_front_page[T.?]:is_news[T.?]',
            'avglinksize',
            'avglinksize:news_front_page[T.1]',
            'avglinksize:news_front_page[T.?]',
            'avglinksize:is_news[T.?]',
            'spelling_errors_ratio',
            'spelling_errors_ratio:news_front_page[T.1]',
            'spelling_errors_ratio:news_front_page[T.?]',
            'spelling_errors_ratio:is_news[T.?]',
            'numwords_in_url',
            'news_front_page[T.1]:numwords_in_url',
            'news_front_page[T.?]:numwords_in_url',
            'numwords_in_url:is_news[T.?]',
            'avglinksize:spelling_errors_ratio',
            'avglinksize:numwords_in_url',
            'spelling_errors_ratio:numwords_in_url'],
           factor_infos={EvalFactor('numwords_in_url'): FactorInfo(factor=EvalFac

### 7.3 Normalize the predictor matrix columns

---

In [66]:
from sklearn.preprocessing import StandardScaler
StandardScaler(X_interactions)

StandardScaler(copy=DesignMatrix with shape (7395, 21)
  Columns:
    ['news_front_page[0]',
     'news_front_page[1]',
     'news_front_page[?]',
     'is_news[T.?]',
     'news_front_page[T.1]:is_news[T.?]',
     'news_front_page[T.?]:is_news[T.?]',
     'avglinksize',
     'avglinksize:news_front_page[T.1]',
  ... 'spelling_errors_ratio:numwords_in_url' (column 20)
  (to view full data, use np.asarray(this_obj)),
        with_mean=True, with_std=True)

### 7.4 Gridsearch a logistic regression to predict accuracy on your new target from the interaction predictors

Include Ridge and Lasso.

---

In [55]:
from sklearn.grid_search import GridSearchCV

logreg = LogisticRegression()
Cs = 1.0/np.logspace(-1,4,20)

search_parameters_log = {
    'penalty': ['l1','l2'],
    'C': Cs,
    'class_weight': [None, 'balanced'],
    'solver': ['liblinear'],
    'n_jobs': [4],
    }
logreg_est = GridSearchCV(logreg, search_parameters_log, cv=10)

In [68]:
logreg_grid = logreg_est.fit(X_interactions,Y)

### 7.5 Build a logistic regression with the optimal parameters, and look at the coefficients

---

### 7.6 Gridsearch parameters for a logistic regression with the same target and predictors, but score based on precision rather than accuracy

Look at the documentation.

---

## [BONUS] 8. Build models predicting from words

This is a bit of the NLP we covered in the pipeline lecture!

---

### 8.1 Choose 'body' or 'title' from the boilerplate to be the basis of your word predictors

You will need to parse the json from the boilerplate field.

---

In [40]:
import json

### 8.2 Use CountVectorizer to create your predictor matrix from the string column

It is up to you what range of ngrams and features, and whether or not you want the columns binary or counts.

---

### 8.3 Gridsearch a logistic regression predicting accuracy of your chosen target category from word predictor matrix

---

### 8.4 Do the same as above, but score the gridsearch based on precision rather than accuracy

---

### 8.5 Build a logistic regression with optimal precision categories

Print out the top 20 or 25 word features as ranked by their coefficients.

---